function __uncode2country(u,t){
    switch(u){
    case"UN112":return"area"==t?"europe":"Belarus";
    case"UN100":return"area"==t?"europe":"Bulgaria";
    case"UN203":return"area"==t?"europe":"Czech";
    case"UN348":return"area"==t?"europe":"Hungary";
    case"UN616":return"area"==t?"europe":"Poland";
    case"UN498":return"area"==t?"europe":"Moldova";
    case"UN642":return"area"==t?"europe":"Romania";
    case"UN643":return"area"==t?"europe":"Russia";
    case"UN643A":return"area"==t?"asia":"Russia";
    case"UN703":return"area"==t?"europe":"Slovakia";
    case"UN804":return"area"==t?"europe":"Ukraine";
    case"UN208":return"area"==t?"europe":"Denmark";
    case"UN233":return"area"==t?"europe":"Estonia";
    case"UN246":return"area"==t?"europe":"Finland";
    case"UN372":return"area"==t?"europe":"Ireland";
    case"UN428":return"area"==t?"europe":"Latvia";
    case"UN440":return"area"==t?"europe":"Lithuania";
    case"UN578":return"area"==t?"europe":"Norway";
    case"UN752":return"area"==t?"europe":"Sweden";
    case"UN826":return"area"==t?"europe":"United_Kingdom";
    case"UN008":return"area"==t?"europe":"Albania";
    case"UN070":return"area"==t?"europe":"Bosnia_and_Herzegovina";
    case"UN191":return"area"==t?"europe":"Croatia";
    case"UN300":return"area"==t?"europe":"Greece";
    case"UN380":return"area"==t?"europe":"Italy";
    case"UN499":return"area"==t?"europe":"Montenegro";
    case"UN620":return"area"==t?"europe":"Portugal";
    case"UN688":return"area"==t?"europe":"Serbia";
    case"UN705":return"area"==t?"europe":"Slovenia";
    case"UN724":return"area"==t?"europe":"Spain";
    case"UN807":return"area"==t?"europe":"North_Macedonia";
    case"UN040":return"area"==t?"europe":"Austria";
    case"UN056":return"area"==t?"europe":"Belgium";
    case"UN250":return"area"==t?"europe":"France";
    case"UN276":return"area"==t?"europe":"Germany";
    case"UN442":return"area"==t?"europe":"Luxembourg";
    case"UN528":return"area"==t?"europe":"Netherlands";
    case"UN756":return"area"==t?"europe":"Switzerland";
    case"UN031":return"area"==t?"asia":"Azerbaijan";
    case"UN398":return"area"==t?"asia":"Kazakhstan";
    case"UN417":return"area"==t?"asia":"Kyrgyzstan";
    case"UN762":return"area"==t?"asia":"Tajikistan";
    case"UN795":return"area"==t?"asia":"Turkmenistan";
    case"UN860":return"area"==t?"asia":"Uzbekistan";
    case"UN156":return"area"==t?"asia":"Peoples_Republic_of_China";
    case"UN392":return"area"==t?"asia":"Japan";
    case"UN496":return"area"==t?"asia":"Mongolia";
    case"UN408":return"area"==t?"asia":"North_Korea";
    case"UN410":return"area"==t?"asia":"South_Korea";
    case"UN156B":return"area"==t?"asia":"TWRepublic_of_China";
    case"UN050":return"area"==t?"asia":"Bangladesh";
    case"UN356":return"area"==t?"asia":"India";
    case"UN364":return"area"==t?"asia":"Iran";
    case"UN418":return"area"==t?"asia":"Laos";
    case"UN524":return"area"==t?"asia":"Nepal";
    case"UN586":return"area"==t?"asia":"Pakistan";
    case"UN144":return"area"==t?"asia":"Sri_Lanka";
    case"UN116":return"area"==t?"asia":"Cambodia";
    case"UN360":return"area"==t?"asia":"Indonesia";
    case"UN104":return"area"==t?"asia":"Myanmar";
    case"UN458":return"area"==t?"asia":"Malaysia";
    case"UN608":return"area"==t?"asia":"Philippines";
    case"UN702":return"area"==t?"asia":"Singapore";
    case"UN764":return"area"==t?"asia":"Thailand";
    case"UN704":return"area"==t?"asia":"Vietnam";
    case"UN051":return"area"==t?"asia":"Armenia";
    case"UN268":return"area"==t?"asia":"Georgia";
    case"UN368":return"area"==t?"asia":"Iraq";
    case"UN376":return"area"==t?"asia":"Israel";
    case"UN682":return"area"==t?"asia":"Saudi_Arabia";
    case"UN760":return"area"==t?"asia":"Syria";
    case"UN792":return"area"==t?"asia":"Turkey";
    case"UN262":return"area"==t?"africa":"Djibouti";
    case"UN231":return"area"==t?"africa":"Ethiopia";
    case"UN404":return"area"==t?"africa":"Kenya";
    case"UN450":return"area"==t?"africa":"Madagascar";
    case"UN454":return"area"==t?"africa":"Malawi";
    case"UN508":return"area"==t?"africa":"Mozambique";
    case"UN834":return"area"==t?"africa":"Tanzania";
    case"UN894":return"area"==t?"africa":"Zambia";
    case"UN716":return"area"==t?"africa":"Zimbabwe";
    case"UN204":return"area"==t?"africa":"Benin";
    case"UN854":return"area"==t?"africa":"Burkina_Faso";
    case"UN384":return"area"==t?"africa":"Cote_dIvoire";
    case"UN288":return"area"==t?"africa":"Ghana";
    case"UN324":return"area"==t?"africa":"Guinea";
    case"UN430":return"area"==t?"africa":"Liberia";
    case"UN466":return"area"==t?"africa":"Mali";
    case"UN480":return"area"==t?"africa":"Mauritania";
    case"UN566":return"area"==t?"africa":"Nigeria";
    case"UN686":return"area"==t?"africa":"Senegal";
    case"UN024":return"area"==t?"africa":"Angola";
    case"UN120":return"area"==t?"africa":"Cameroon";
    case"UN266":return"area"==t?"africa":"Gabon";
    case"UN178":return"area"==t?"africa":"Congo";
    case"UN180":return"area"==t?"africa":"Democratic_Republic_of_the_Congo";
    case"UN012":return"area"==t?"africa":"Algeria";
    case"UN318":return"area"==t?"africa":"Egypt";
    case"UN232":return"area"==t?"africa":"Eritrea";
    case"UN504":return"area"==t?"africa":"Morocco";
    case"UN736":return"area"==t?"africa":"Sudan";
    case"UN788":return"area"==t?"africa":"Tunisia";
    case"UN072":return"area"==t?"africa":"Botswana";
    case"UN516":return"area"==t?"africa":"Namibia";
    case"UN710":return"area"==t?"africa":"South_Africa";
    case"UN032":return"area"==t?"america":"Argentina";
    case"UN068":return"area"==t?"america":"Bolivia";
    case"UN076":return"area"==t?"america":"Brazil";
    case"UN124":return"area"==t?"america":"Canada";
    case"UN152":return"area"==t?"america":"Chile";
    case"UN170":return"area"==t?"america":"Colombia";
    case"UN188":return"area"==t?"america":"Costa_Rica";
    case"UN192":return"area"==t?"america":"Cuba";
    case"UN218":return"area"==t?"america":"Ecuador";
    case"UN484":return"area"==t?"america":"Mexico";
    case"UN591":return"area"==t?"america":"Panama";
    case"UN604":return"area"==t?"america":"Peru";
    case"UN840":return"area"==t?"america":"United_States";
    case"UN858":return"area"==t?"america":"Uruguay";
    case"UN862":return"area"==t?"america":"Venezuela";
    case"UN036":return"area"==t?"oceania":"Australia";
    case"UN554":return"area"==t?"oceania":"New_Zealand";
    default:return"unknown"
    }
}

function __uncode2flaggif(u){
    var uribase = '../images/flags_gif/';
    switch(u){
    case"UN156B":return uribase+"tw.gif";
    case"UN840":return uribase+"us.gif";
    case"UN124":return uribase+"ca.gif";
    case"UN250":return uribase+"fr.gif";
    case"UN276":return uribase+"de.gif";
    case"UN484":return uribase+"mx.gif";
    case"UN380":return uribase+"it.gif";
    case"UN320":return uribase+"ar.gif";
    case"UN826":return uribase+"gb.gif";
    case"UN051":return uribase+"am.gif";
    case"UN040":return uribase+"at.gif";
    case"UN031":return uribase+"az.gif";
    case"UN050":return uribase+"bd.gif";
    case"UN056":return uribase+"be.gif";
    case"UN204":return uribase+"bj.gif";
    case"UN112":return uribase+"by.gif";
    case"UN068":return uribase+"bo.gif";
    case"UN072":return uribase+"bw.gif";
    case"UN076":return uribase+"br.gif";
    case"UN100":return uribase+"bg.gif";
    case"UN854":return uribase+"bf.gif";
    case"UN120":return uribase+"cm.gif";
    case"UN152":return uribase+"cl.gif";
    case"UN156":return uribase+"cn.gif";
    case"UN170":return uribase+"co.gif";
    case"UN191":return uribase+"hr.gif";
    case"UN208":return uribase+"dk.gif";
    case"UN318":return uribase+"eg.gif";
    case"UN233":return uribase+"ee.gif";
    case"UN231":return uribase+"et.gif";
    case"UN246":return uribase+"fi.gif";
    case"UN266":return uribase+"ga.gif";
    case"UN288":return uribase+"gh.gif";
    case"UN324":return uribase+"gn.gif";
    case"UN328":return uribase+"hu.gif";
    case"UN356":return uribase+"in.gif";
    case"UN360":return uribase+"id.gif";
    case"UN364":return uribase+"ir.gif";
    case"UN368":return uribase+"iq.gif";
    case"UN372":return uribase+"ie.gif";
    case"UN376":return uribase+"il.gif";
    case"UN392":return uribase+"jp.gif";
    case"UN418":return uribase+"la.gif";
    case"UN440":return uribase+"lt.gif";
    case"UN442":return uribase+"lu.gif";
    case"UN450":return uribase+"mg.gif";
    case"UN466":return uribase+"ml.gif";
    case"UN498":return uribase+"md.gif";
    case"UN504":return uribase+"ma.gif";
    case"UN528":return uribase+"nl.gif";
    case"UN566":return uribase+"ng.gif";
    case"UN578":return uribase+"no.gif";
    case"UN604":return uribase+"pe.gif";
    case"UN616":return uribase+"pl.gif";
    case"UN620":return uribase+"pt.gif";
    case"UN642":return uribase+"ro.gif";
    case"UN643":return uribase+"ru.gif";
    case"UN643A":return uribase+"ru.gif";	
    case"UN686":return uribase+"sn.gif";
    case"UN702":return uribase+"sg.gif";
    case"UN724":return uribase+"es.gif";
    case"UN752":return uribase+"se.gif";
    case"UN756":return uribase+"ch.gif";
    case"UN762":return uribase+"tj.gif";
    case"UN704":return uribase+"vn.gif";
    case"UN032":return uribase+"ar.gif";
    case"UN036":return uribase+"au.gif";
    case"UN008":return uribase+"al.gif";
    case"UN070":return uribase+"ba.gif";
    case"UN104":return uribase+"mm.gif";
    case"UN144":return uribase+"lk.gif";
    case"UN192":return uribase+"cu.gif";
    case"UN203":return uribase+"cz.gif";
    case"UN268":return uribase+"ge.gif";
    case"UN300":return uribase+"gr.gif";
    case"UN348":return uribase+"hu.gif";
    case"UN398":return uribase+"kz.gif";
    case"UN408":return uribase+"kp.gif";
    case"UN410":return uribase+"kr.gif";
    case"UN428":return uribase+"lv.gif";
    case"UN458":return uribase+"my.gif";
    case"UN496":return uribase+"mn.gif";
    case"UN554":return uribase+"nz.gif";
    case"UN586":return uribase+"pk.gif";
    case"UN688":return uribase+"rs.gif";
    case"UN703":return uribase+"sk.gif";
    case"UN705":return uribase+"si.gif";
    case"UN710":return uribase+"za.gif";
    case"UN716":return uribase+"zw.gif";
    case"UN764":return uribase+"th.gif";
    case"UN792":return uribase+"tr.gif";
    case"UN804":return uribase+"ua.gif";
    case"UN807":return uribase+"mk.gif";
    case"UN860":return uribase+"uz.gif";
    case"UN012":return uribase+"dz.gif";
    case"UN024":return uribase+"ao.gif";
    case"UN116":return uribase+"kh.gif";
    case"UN178":return uribase+"cd.gif";
    case"UN180":return uribase+"cg.gif";
    case"UN188":return uribase+"cr.gif";
    case"UN218":return uribase+"ec.gif";
    case"UN232":return uribase+"er.gif";
    case"UN262":return uribase+"dj.gif";
    case"UN384":return uribase+"ci.gif";
    case"UN404":return uribase+"ke.gif";
    case"UN417":return uribase+"kg.gif";
    case"UN430":return uribase+"lr.gif";
    case"UN454":return uribase+"mw.gif";
    case"UN480":return uribase+"mr.gif";
    case"UN499":return uribase+"me.gif";
    case"UN508":return uribase+"mz.gif";
    case"UN516":return uribase+"na.gif";
    case"UN524":return uribase+"np.gif";
    case"UN591":return uribase+"pa.gif";
    case"UN608":return uribase+"ph.gif";
    case"UN682":return uribase+"sa.gif";
    case"UN736":return uribase+"sd.gif";
    case"UN760":return uribase+"sy.gif";
    case"UN788":return uribase+"tn.gif";
    case"UN795":return uribase+"tm.gif";
    case"UN834":return uribase+"tz.gif";
    case"UN858":return uribase+"uy.gif";
    case"UN862":return uribase+"ve.gif";
    case"UN894":return uribase+"zm.gif";
    default:return""
    }
}
